version: "3.9"

services:
  biznatop-app:
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        DOMAIN: ${DOMAIN}
        SESSION_SECRET: ${SESSION_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        S3_REGION: ${S3_REGION}
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        S3_ENDPOINT_EU: ${S3_ENDPOINT_EU}
        S3_HOSTNAME: ${S3_HOSTNAME}
        WEB_PUSH_EMAIL: ${WEB_PUSH_EMAIL}
        NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: ${NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY}
        WEB_PUSH_PRIVATE_KEY: ${WEB_PUSH_PRIVATE_KEY}
    environment:
      NODE_ENV: ${NODE_ENV}
      DOMAIN: ${DOMAIN}
      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT_EU: ${S3_ENDPOINT_EU}
      S3_HOSTNAME: ${S3_HOSTNAME}
      WEB_PUSH_EMAIL: ${WEB_PUSH_EMAIL}
      NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: ${NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY}
      WEB_PUSH_PRIVATE_KEY: ${WEB_PUSH_PRIVATE_KEY}
    depends_on:
      biznatop-db:
        condition: service_healthy
    ports:
      - "3000:8080"
    restart: always
    networks:
      - bizna-secure

  biznatop-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: biznatop
      POSTGRES_PASSWORD: 001Bizna
      POSTGRES_DB: biznadb
    volumes:
      - pgdata:/var/lib/postgresql/data
    # No ports exposed to the host, only accessible within the Docker network
    # ports:
    #   - "5000:5432"
    networks:
      - bizna-secure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biznatop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  bizna-secure:
    driver: bridge