
services:
  app:
    build:
      context: .
      args:
        - GITHUB_PAT
        - GITHUB_REPO
        - NODE_ENV
        - NEXT_RUNTIME
        - DOMAIN
        - SESSION_SECRET
        - DATABASE_URL
        - S3_REGION
        - S3_ENDPOINT
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME
        - S3_ENDPOINT_EU
        - S3_HOSTNAME
        - WEB_PUSH_EMAIL
        - NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY
        - WEB_PUSH_PRIVATE_KEY
    env_file:
      - .env
    ports:
      - "3000:8080"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: